#ifndef TRANSFER_FILE_TRANSFER_H
#define TRANSFER_FILE_TRANSFER_H

#define MAX_LINE 4096
#define LINSTENPORT 7788
#define SERVERPORT 8877
#define BUFFSIZE 4096
#define MAX_PATHLEN 500
#define MAX_IP 20
#endif //TRANSFER_FILE_TRANSFER_H
